name: Production Deployment

permissions:
  actions: read
  contents: read
  id-token: write

env:
  CI: true
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_ORG_ID }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  API_SENTRY_DSN: ${{ secrets.API_SENTRY_DSN }}
  ENGINE_SENTRY_DSN: ${{ secrets.ENGINE_SENTRY_DSN }}
  INGESTION_SENTRY_DSN: ${{ secrets.INGESTION_SENTRY_DSN }}

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }}-${{ github.event.number || github.sha }}'
      cancel-in-progress: true
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/cache@v4
        with:
          path: .turbo
          key: '${{ runner.os }}-turbo-${{ github.sha }}'
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    concurrency:
      group: '${{ github.workflow }}-${{ github.event.number || github.sha }}'
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/cache@v4
        with:
          path: .turbo
          key: '${{ runner.os }}-turbo-${{ github.sha }}'
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm test

  deploy-engine:
    runs-on: ubuntu-latest
    needs: [build, tests]
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/cache@v4
        with:
          path: .turbo
          key: '${{ runner.os }}-turbo-${{ github.sha }}'
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/atlas-deploy-role
          aws-region: eu-west-1

      - run: pnpm cdk:network -- deploy --all --require-approval never

      - run: pnpm cdk:migrations -- deploy --all --require-approval never

      - run: pnpm cdk:engine -- deploy --all --require-approval never

  deploy-endpoints:
    runs-on: ubuntu-latest
    needs: [build, tests, deploy-engine]
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/cache@v4
        with:
          path: .turbo
          key: '${{ runner.os }}-turbo-${{ github.sha }}'
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/atlas-deploy-role
          aws-region: eu-west-1

      - run: pnpm cdk:api -- deploy --all --require-approval never

      - run: pnpm cdk:ingestion -- deploy --all --require-approval never

  deploy-app:
    runs-on: ubuntu-latest
    needs: [build, tests, deploy-engine]
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/cache@v4
        with:
          path: .turbo
          key: '${{ runner.os }}-turbo-${{ github.sha }}'
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
